name: Lint rst

on:
    push:
        paths: ['**/**.rst']
    pull_request:
        paths: ['**/**.rst']

jobs:
    doctor-rst:
        name: DOCtor-RST
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v4

            - name: DOCtor-RST
              uses: docker://oskarstark/doctor-rst
              with:
                  args: --short --error-format=github
              env:
                  DOCS_DIR: 'doc/'
